import {
  Atom,
  BookOpen,
  Brain,
  Code,
  Dna,
  FlaskConical,
  Gavel,
  Globe,
  GraduationCap,
  Landmark,
  Languages,
  Music,
  Palette,
  Scale,
  Scroll,
  Sigma,
  Sprout,
  Stethoscope,
  TrendingUp,
  Wrench,
  type LucideIcon,
} from 'lucide-react'

const BY_SUBJECT: Record<string, LucideIcon> = {
  COMP: Code, SOFT: Code, CCOM: Code, ECSE: Code, INSY: Code,
  MATH: Sigma,
  STAT: TrendingUp, ECON: TrendingUp, ACCT: TrendingUp, FINE: TrendingUp,
  MGCR: TrendingUp, MRKT: TrendingUp, ORGB: TrendingUp, MGPO: TrendingUp, BUSA: TrendingUp,
  POLI: Landmark, INTD: Landmark, PUBP: Landmark,
  PSYC: Brain, NEUR: Brain, COGS: Brain,
  BIOL: Dna, BCHM: Dna, MIMM: Dna, MICR: Dna, PHGY: Dna, ANAT: Dna,
  CHEM: FlaskConical, CHEE: FlaskConical,
  PHYS: Atom, ATOC: Atom, EPSC: Atom,
  HIST: Scroll, CLAS: Scroll, ARTH: Scroll,
  ENGL: BookOpen, WCOM: BookOpen, CANS: BookOpen,
  PHIL: Scale, RELG: Scale, JWST: Scale, ISLA: Scale,
  LAWG: Gavel, LAW: Gavel,
  ANTH: Globe, SOCI: Globe, GEOG: Globe, URBP: Globe, ENVR: Globe,
  MUAR: Music, MUSP: Music, MUGT: Music,
  ARTS: Palette, FMST: Palette, CATH: Palette,
  NURS: Stethoscope, MDCN: Stethoscope, PHTH: Stethoscope, POTH: Stethoscope, NUTR: Stethoscope,
  FREN: Languages, SPAN: Languages, GERM: Languages, ITAL: Languages, RUSS: Languages,
  LING: Languages, EAST: Languages, HISP: Languages,
  MECH: Wrench, CIVE: Wrench, ELEC: Wrench, MIME: Wrench, BIEN: Wrench, ARCH: Wrench,
  AGRI: Sprout, PLNT: Sprout, SOIL: Sprout, WILD: Sprout, FDSC: Sprout,
  EDPE: GraduationCap, EDEC: GraduationCap, EDPT: GraduationCap,
}

export const subjectIcon = (code: string): LucideIcon =>
  BY_SUBJECT[code.trim().toUpperCase().split(/\s+/)[0]] ?? BookOpen
